trigger:
- main

pool:
  name: Default

variables:
  project-name-dev: 'my-dev'
  project-name-uat: 'my-uat'
  image-name: 'helloworld-java'

stages:
- stage: Build
  displayName: Build and Push Image
  jobs:
  - job: BuildAndPushJob
    displayName: Build and Push Job
    steps:
    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        command: 'build'
        containerRegistry: 'Azure Container Registry'
        buildContext: '**'
        repository: '$(project-name-dev)/$(image-name)'
        Dockerfile: 'Dockerfile'
        tags: $(Build.BuildId)
    - task: Docker@2
      displayName: 'Push Docker image to Azure Container Registry'
      inputs:
        command: 'push'
        containerRegistry: 'Azure Container Registry'
        repository: '$(project-name-dev)/$(image-name)'
        tags: $(Build.BuildId)
